server:
  port: 9090

# ???????????????????????9090????????????9090??8080
# mysql configuration
# url ?????3306???????????
# nwy is database

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    # 这个需要配置，不然会出现一下报错，springboot2.7 需要配置
    # org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
  datasource:
    url: jdbc:mysql://localhost:3306/nwy?serverTimezone=GMT%2b8
    username: root
    password: nwy0522.
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 只要调用接口，就会打印

#springfox.documentation.swagger-ui.enabled: true