server:
  port: 9090

# ???????????????????????9090????????????9090??8080
# mysql configuration
# url ?????3306???????????
# nwy is database

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nwy?serverTimezone=GMT%2b8
    username: root
    password: nwy0522.
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml